#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python310/python

import sys

exec_run=False
if getattr(sys,'frozen', False):
    os.chdir(sys._MEIPASS)
    exec_run=True

import os
os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = 'hide' 
#os.environ['SDL_VIDEO_WINDOW_POS']="%d,%d" % (0,0)
import pygame
from Pong import pong
from SpaceRace import spacerace
from QuadraPong import quadrapong
import menu0
import settings

all_quit=False
pygame.init()
settings_dict={}
settings_dict=settings.load_settings()
settings.set_settings(settings_dict)

while not all_quit:
    # Initialize the game, music, timer, and screen
    screen = pygame.display.set_mode((800,600))

    # Load the menu. Continue reloading the menu until an option is selected that requests
    # the game to load.
    if len(sys.argv) == 1:
        quickstart=False
        menu_run=True
        while menu_run:
            menu_run,game,all_quit,settings_dict=menu0.run_menu('BrowGames',screen,settings_dict)
            settings.set_settings(settings_dict)
    else:
        game=sys.argv[1]
        quickstart=True

    if game == 'Pong':
        settings_dict=pong.run("Original",settings_dict,quickstart=quickstart)
    elif game == 'Space Race':
        settings_dict=spacerace.run("Original",settings_dict,quickstart=quickstart)
    elif game == 'Pong Doubles':
        settings_dict=pong.run("Doubles",settings_dict,quickstart=quickstart)
    elif game == 'Pong Soccer':
        settings_dict=pong.run("Pong Soccer",settings_dict,quickstart=quickstart)
    elif game == 'Crazy Foot':
        settings_dict=pong.run("Crazy Foot",settings_dict,quickstart=quickstart)
    elif game == 'Quadrapong':
        settings_dict=quadrapong.run("Original",settings_dict,quickstart=quickstart)

    if quickstart:
        all_quit=True
 
