#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python310/python

import sys

exec_run=False
if getattr(sys,'frozen', False):
    os.chdir(sys._MEIPASS)
    exec_run=True

import os
os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = 'hide' 
#os.environ['SDL_VIDEO_WINDOW_POS']="%d,%d" % (0,0)
import pygame
from Pong import pong
from SpaceRace import spacerace
from QuadraPong import quadrapong
import menu0
import settings

all_quit=False
pygame.init()
settings_dict={}
settings_dict=settings.load_settings()
settings.set_settings(settings_dict)

while not all_quit:
    # Initialize the game, music, timer, and screen
    screen = pygame.display.set_mode((800,600))

    # Load the menu. Continue reloading the menu until an option is selected that requests
    # the game to load.
    if len(sys.argv) == 1:
        quickstart=False
        menu_run=True
        while menu_run:
            menu_run,game,all_quit,settings_dict=menu0.run_menu('BrowGames',screen,settings_dict)
            settings.set_settings(settings_dict)
    else:
        game=sys.argv[1]
        quickstart=True

    back_to_main=False
    pars=None
    while not back_to_main and not all_quit:
        back_to_main=True
        if game == 'Pong':
            settings_dict,back_to_main,pars=pong.run(pars,settings_dict,quickstart=quickstart,default="Original")
        elif game == 'Space Race':
            settings_dict,back_to_main,pars=spacerace.run(pars,settings_dict,quickstart=quickstart,default="Original")
        elif game == 'Pong Doubles':
            settings_dict,back_to_main,pars=pong.run(pars,settings_dict,quickstart=quickstart,default="Doubles")
        elif game == 'Pong Soccer':
            settings_dict,back_to_main,pars=pong.run(pars,settings_dict,quickstart=quickstart,default="Pong Soccer")
        elif game == 'Crazy Foot':
            settings_dict,back_to_main,pars=pong.run(pars,settings_dict,quickstart=quickstart,default="Crazy Foot")
        elif game == 'Quadrapong':
            settings_dict,back_to_main,pars=quadrapong.run(pars,settings_dict,quickstart=quickstart,default="Original")

        if quickstart:
            all_quit=True
 
